import { Router } from 'express';
import authRoutes from './auth.routes';
import clientesRoutes from './clientes.routes';
import dashboardRoutes from './dashboard.routes';
import solicitacoesRoutes from './solicitacoes.routes';
import orcamentosRoutes from './orcamentos.routes';
import projetosRoutes from './projetos.routes';
import pagamentosRoutes from './pagamentos.routes';
import arquivosRoutes from './arquivos.routes';
import relatoriosRoutes from './relatorios.routes';
import calendarioRoutes from './calendario.routes';
import notificacoesRoutes from './notificacoes.routes';
import portalRoutes from './portal.routes';
import billingRoutes from './billing.routes';
import nfseRoutes from './nfse.routes';
import exportRoutes from './export.routes';
import timeEntriesRoutes from './time-entries.routes';
import despesasRoutes from './despesas.routes';
import templatesRoutes from './templates.routes';

const router = Router();

router.use('/auth', authRoutes);
router.use('/clientes', clientesRoutes);
router.use('/dashboard', dashboardRoutes);
router.use('/solicitacoes', solicitacoesRoutes);
router.use('/orcamentos', orcamentosRoutes);
router.use('/projetos', projetosRoutes);
router.use('/pagamentos', pagamentosRoutes);
router.use('/arquivos', arquivosRoutes);
router.use('/relatorios', relatoriosRoutes);
router.use('/calendario', calendarioRoutes);
router.use('/notificacoes', notificacoesRoutes);
router.use('/portal', portalRoutes);
router.use('/billing', billingRoutes);
router.use('/notas-fiscais', nfseRoutes);
router.use('/export', exportRoutes);
router.use('/time-entries', timeEntriesRoutes);
router.use('/despesas', despesasRoutes);
router.use('/templates', templatesRoutes);

export default router;